version: 2
jobs:
  build:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: apt-get update
      - run:
          name: Install dependencies
          command: apt-get install -y libavcodec-dev libavformat-dev libavutil-dev qtbase5-dev libqcustomplot-dev liblcms2-dev libpugixml-dev libfftw3-dev libjpeg-dev libpng-dev liblzma-dev libqt5x11extras5-dev libboost-dev libeigen3-dev libx11-xcb-dev libxcb-util0-dev
      - run:
          name: Setup build folder
          command: mkdir -p build && cd build
      - run:
          name: Configure project for Release
          command: cmake .. -DCMAKE_BUILD_TYPE=RELEASE
      - run:
          name: Compile project
          command: make